#!/usr/bin/env python

import wepcracker

__author__ = 'shane'

# N id the size of the seed array for KSA
N = 256


def ksa(k):
    """

    :param k: the byte array key (IV prepended to the secret key)
    :return: a pseudo random permutation of [0, 1, 2,..., 255]
    """
    s = [i for i in range(N)]
    j = 0
    for i in range(N):
        j = (j + s[i] + k[i % len(k)]) % N
        # Swap(s[i], s[j])
        temp = s[i]
        s[i] = s[j]
        s[j] = temp
    return s


def prga(s, data_length):
    """

    :param s: a pseudo random permutation of [0, 1, 2,..., 255] generated by ksa
    :param data_length: length of the packet data (message + checksum) in bytes
    :return: a byte array to XOR the packet data with
    """
    z = []
    i = 0
    j = 0
    for x in range(data_length):
        i = (i+1) % N
        j = (j + s[i+1]) % N
        # Swap(s[i], s[j])
        temp = s[i]
        s[i] = s[j]
        s[j] = temp
        z.append(s[(s[i] + s[j]) % N])
    return z

# TODO: Generate random WEP key and random wep packets.
# then test wepcracker.py
def main():
    return

if __name__ == '__main__':
    main()